### ISSUE TITLE
Everything on track to submit?

### ISSUE THREAD

**Issue by dalessr** [CS2103JAN2018-T09-B1/main#214]
Everything on track to submit? Remember to read submission instructions carefully and plan to finish submissions at least few hours before the deadline.

Here is a list for your reference (made it myself, might missed something):
- Tag the last commit as `v1.5` on GitHub
- Build the latest jar file, change file name and upload to ivle
- Finalize UG (all features specifications) DG (feature implementations, appendix for testing instructions), change file name and upload to ivle
- Update `AboutUs` page on GitHub (full names, GitHub and Portfolio links)
- Finalize Project Portfolio Page (PPP) on GitHub, change file name and upload to ivle
- Collate code (main, test, unused...), update collated files on GitHub, remember to add links in PPP
- Final release v1.5

All the best for the final submission and demo 👍

**Comment by kengsengg** [comment]
Thank you! :)
